export { Banner } from './components/Banner/index'
export { Button } from './components/Button/index'
export { ButtonRadiusIcon } from './components/ButtonRadiusIcon/index'
export { ButtonRound } from './components/ButtonRound/index'
export { IconWrapper } from './components/IconWrapper/index'
export { Modal } from './components/Modal/index'
export { Paragraph } from './components/Paragraph/index'
export { Tabs } from './components/Tabs/index'
export { theme } from './components/Themes/index'
export { Title } from './components/Title/index'
export { Table } from './components/Table/index'
export { Paginate } from './components/Paginate/index'

export { docCheckSVG, alertSVG, commentSVG, imageSVG, closeSVG } from './assets/icon/index'
